In [240]:
import numpy as np

# Array Basics
## 1 Dimentional Array

In [241]:

array1 = np.array([1,2,3])
print('Array Type {0} , Shape {1}, Dimension {2} '.format(array1.dtype, array1.shape, array1.ndim))

Array Type int32 , Shape (3,), Dimension 1 


## 2 Dimensional Array

In [242]:
array2 = np.array([[1,2,3], [4,5,6]])
print('Array Type {0} , Shape {1}, Dimension {2} '.format(array2.dtype, array2.shape, array2.ndim))

Array Type int32 , Shape (2, 3), Dimension 2 


In [243]:
arr = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(arr)

# Get a specific element [r, c]
arr[1, 5]

# Get a specific row 
arr[0, :]

# Get a specific column
arr[:, 2]

# startindex:endindex:stepsize
arr[0, 1:-1:2]

#assign a value for row 1 and column 5
arr[1,5] = 20

#assign the column 2 
arr[:,2] = [1,2]
print(arr)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [244]:
# All 0s matrix
arr = np.zeros((2,3))
print("arr - numpy zeroes 2 * 3 \n", arr)

# All 1s matrix
arr = np.ones((4,2,2), dtype='int32')
print("arr - numpy ones 4 * 2 * 2 \n", arr)

# Any other number
arr = np.full((2,3), 99)
print("arr - numpy 99 \n", arr)

# Any other number (full_like)
arr = np.full_like(arr, 4)
print("arr - numpy full like  \n", arr)

# Random decimal numbers
arr = np.random.rand(4,2)
print("arr - numpy random \n", arr)


# Random Integer values
arr = np.random.randint(-4,8, size=(3,3))
print("arr - numpy random int \n", arr)

# The identity matrix
arr = np.identity(5)
print("arr - numpy identity \n", arr)

# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print("Repeat array \n",  r1, " shape - " , r1.shape)


output = np.ones((5,5))
print("Output \n" , output)

z = np.zeros((3,3))
z[1,1] = 9
print("Z = \n", z)

output[1:-1,1:-1] = z
print("Final  output \n" , output)


arr - numpy zeroes 2 * 3 
 [[0. 0. 0.]
 [0. 0. 0.]]
arr - numpy ones 4 * 2 * 2 
 [[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
arr - numpy 99 
 [[99 99 99]
 [99 99 99]]
arr - numpy full like  
 [[4 4 4]
 [4 4 4]]
arr - numpy random 
 [[0.37952817 0.31414174]
 [0.62978312 0.91738562]
 [0.31309508 0.3699619 ]
 [0.93236732 0.56642955]]
arr - numpy random int 
 [[ 2  4 -4]
 [ 7  3  7]
 [ 2  4 -4]]
arr - numpy identity 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Repeat array 
 [[1 2 3]
 [1 2 3]
 [1 2 3]]  shape -  (3, 3)
Output 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Z = 
 [[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
Final  output 
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## 3 Dimensional Array

In [245]:
array3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print('Array Type {0} , Shape {1}, Dimension {2} '.format(array3.dtype, array3.shape, array3.ndim))

Array Type int32 , Shape (2, 2, 3), Dimension 3 


In [246]:
arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

# Get specific element (work outside in)
print(arr[0,1,1])

# replace 
arr[:,1,:] = [[9,9],[8,8]]

print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [247]:
a = np.array([1,2,3,4])
print("Math Operation ", a)

a = a + 2
print("Math Operation add ", a)

a= a - 2
print("Math Operation sub ", a)

a = a * 2
print("Math Operation mul ", a)

a = a / 2
print("Math Operation div ", a)

b = np.array([1,0,1,0])
c = a + b
print("Math Operation a + b ", c)

a= a ** 2
print("Math Operation power ", a)


Math Operation  [1 2 3 4]
Math Operation add  [3 4 5 6]
Math Operation sub  [1 2 3 4]
Math Operation mul  [2 4 6 8]
Math Operation div  [1. 2. 3. 4.]
Math Operation a + b  [2. 2. 4. 4.]
Math Operation power  [ 1.  4.  9. 16.]


In [248]:
# Take the sin
np.cos(a)

# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

"""##### Linear Algebra"""

a = np.ones((2,3))
print("a " , a)

b = np.full((3,2), 2)
print("b ", b)

print("matmul a and b ", np.matmul(a,b))
print("dot a and b ", np.dot(a,b))
print("vdot a and b ", np.vdot(a,b))
print("a @ b ", a@b)
print("outer a @ b ", np.outer(a,b))


# Find the determinant
c = np.identity(3)
np.linalg.det(c)

a  [[1. 1. 1.]
 [1. 1. 1.]]
b  [[2 2]
 [2 2]
 [2 2]]
matmul a and b  [[6. 6.]
 [6. 6.]]
dot a and b  [[6. 6.]
 [6. 6.]]
vdot a and b  12.0
a @ b  [[6. 6.]
 [6. 6.]]
outer a @ b  [[2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2.]]


1.0

In [249]:
## Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

# Determinant
# Trace
# Singular Vector Decomposition
# Eigenvalues
# Matrix Norm
# Inverse
# Etc...

"""##### Statistics"""

stats = np.array([[1,2,3],[4,5,6]])
stats

x = np.min(stats)
print("x " , x)

y = np.max(stats, axis=1)
print("y " , y)


z = np.sum(stats, axis=0)
print("z " , z)

"""### Reorganizing Arrays"""

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

vs = np.vstack([v1,v2,v1,v2])
print("v1" , v1)
print("v2" , v2)
print("vs " , vs)

# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

hs = np.hstack((h1,h2))
print("h1" , h1)
print("h2" , h2)
print("hs " , hs)


x  1
y  [3 6]
z  [5 7 9]
[[1 2 3 4]
 [5 6 7 8]]
v1 [1 2 3 4]
v2 [5 6 7 8]
vs  [[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]
h1 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
h2 [[0. 0.]
 [0. 0.]]
hs  [[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]
